# configurations for downloader
# configurations for downloader. Do not move this file.# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
# configurations for downloader. Do not move this file. 
